port:  5000
markdown: kramdown
name: "Brentano Elementary"
url: "localhost:5000"
encoding: utf-8
timezone: America/Chicago
description: ""
permalink: /:categories/:title
gems:
  - jekyll-redirect-from
