port:  5000
markdown: kramdown
name: "Brentano Math and Science Academy"
title: "Brentano Math and Science Academy"
description: "An extraordinary neighborhood school in the heart of Logan Square"
url: "http://brentanomathandscienceacademy.org"
encoding: utf-8
timezone: America/Chicago
description: ""
permalink: /:categories/:title
gems:
  - jekyll-redirect-from
